### ISSUE TITLE
Newer aimbot version makes it fidget more

### ISSUE THREAD

**Issue by BlTWISE** [IceHacks/SurvivCheatInjector#298]
**Describe the bug**
When holding down on the aim (like for instance, bump fire, or auto shooting with an ak47) the aimbot fidgets a lot and is much more obvious to detect than before.

**Expected behavior**
It should not fidget, especially with the legit setting on. It didn't fidget before.

**Screenshots**

**Cheat version**
2.0.6

**Chromium version**
79.0.3945.130 (Official Build) (64-bit) (cohort: Stable)

**Comment by zerodark088888** [comment]
i have few problems with aim bot too like some times i get stick to wall  when enemy is behind wall
idk why ? o.o

and when followbot is off why it is following enemy ? 

and some times aim bot dont auto shot and some times it auto shot


i m sorry to say it 

ur hack is soo gud and i really love melee hack   and other things but idk why but aim bot have some issues 

ur really work hard to keep it updated pls 

but it have few issues when i use idk wht is reason 

but anyways thanks for making hack it help alot hope u can make it more perfect one day 

i play in asia server and its like there is only 40 players per match  and its like i hardly get 4 kills with hack on average games


thanks for making hack anyways

**Comment by pilgrimoflight** [comment]
I have problem with latest cheat aim too. Its works very bad. I can make video bout it.
My friend use same settings and his aim works perfect. 
Someone has same problem? Its impossible to shoot someone ))

**Comment by godiclili** [comment]
I am not sure if I am the only one facing this problem...
Snipers do not work in autoaim since 2.0.5. The gun keeps pointing to enemy but can't shoot, even if I click the mouse there is no bullet out
(and I am sure I cleared cookies and then updated to 2.0.6)
(It is a good opportunity for me to practice using guns other than snipers btw...

**Comment by zerodark088888** [comment]
idk this hack is so cool but there is some issue with aim bot idk what is reason
i have been using pro hack for nearly 4 months or more and it was quit easy to use 
but it dont work anymore
anyways i love this hack as it have melee hack and ggrenade timer and other cool things
but idk why the aim bot is not much perfect even some times when there is  enemy is not moving or just totally standing it hit enemy perfectly but when they are moving its like it cant shot and  with sniper its not perfect 
sorry to say and thanks for ur hard work to keep hack updated

**Comment by humphreygaming** [comment]
@zerodark088888 

**i have few problems with aim bot too like some times i get stick to wall when enemy is behind wall
idk why ? o.o**: This is because of auto-attack. Hold Right click to temporarly disable it

**and when followbot is off why it is following enemy**: Follow bot is a different thing on its own. Don't use it if you don't know how to.

**and some times aim bot dont auto shot and some times it auto shot**: Play around with collisions

**ur hack is soo gud and i really love melee hack and other things but idk why but aim bot have some issues**: Aimbot V2 is a newer version of an aimbot and is still in developement


**i play in asia server and its like there is only 40 players per match and its like i hardly get 4 kills with hack on average games**: You are trash

**Comment by zerodark088888** [comment]
well i might not use this hack for now becuz its in development 
thanks for making hack

**Comment by IceHacks** [comment]
that's ok. It means you won't bother me with complaint "issues"

**Comment by BlTWISE** [comment]
Out of curiosity why was this closed? The issue is still active and users are posting duplicates.
