### ISSUE TITLE
Source code request

### ISSUE THREAD

**Issue by acimanx** [IceHacks/SurvivCheatInjector#38]
@IceHacks please upload SurvivCheatInjector source.
I would like to use & improve it.

**Comment by u1qqlv** [comment]
I don't think he will agree, because he will not want the source code to be in the hands of the devs of the surviv.io team... or he maybe is interested into monetizing the hack so this could be the second reason.

**Comment by u1qqlv** [comment]
my hack is discontinued but it is open source, you can check if you want - https://github.com/u1qqlv/SURVIV.IO-PRO-HACK
Note: is not working and may freeze if you fix it...

**Comment by acimanx** [comment]
Hi @u1qqlv ! Didn't expect you to answer here. Honestly, I am glad that you answer. I've used your hack before, when it's still worked. 
Isn't your code compiled and obfuscated too? I look at files ending with *clean_code.js now, and wonder how did you manage to figure that out?

**Comment by humphreygaming** [comment]
Nu uh, no way, source will not be uploaded because of security reasons even if you "want to improve it". However, if you want the RAW sources from where this source was based off, then go check out gatorix's Surviv Plus hack under the aimbot part. Some other parts were also based off of zbot473's Surviv Hack (which is deleted probably). Most of the hack base was made by IceHacks himself and, knowing him, won't give his source code to anyone. @acimanx

**Comment by IceHacks** [comment]
@acimanx Sure.
