### ISSUE TITLE
A Note that is NOT "Hackers are trash"

### ISSUE THREAD

**Issue by Viswas-Programs** [IceHacks/SurvivCheatInjector#933]
And this note is not any kind of "Hackers are trash".
Now that the game servers are shut down, by Kongregate, what are you going to do with this from now?
Now, their servers are down, only the website is up (idk how that's the case but it is). So nobody can join a game, how is this cheat going to be any profit from now on?
There should be a game existing, to make anything related to it (mods or in this case, unfair cheats)

**Comment by russyboy1** [comment]
please collect skin

**Comment by humphreygaming** [comment]
Been a hot minute, err, a year. But better late than never!

So, no future plans. None for a long time, quite possibly ever. I think it's safe to say almost everyone who worked on this project has moved on with their lives. Most who played surviv probably did so as well. The cheat wasn't for profit either, so there wasn't much of an incentive to keep it going. Plus, it did pretty well by itself, only dying because the game itself died.

Suffice to say, it's the end.
